### ISSUE TITLE
[Bug]: error trying to install pymilvus - AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by rmundkowsky** [milvus-io/pymilvus#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Running on Windows 10 Enterprise running Python 3.12.0:

pip install "pymilvus>=2.3.1"

Causes the below error:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\commands\install.py", line 285, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\req_command.py", line 75, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\req_command.py", line 89, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\network\session.py", line 282, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\network\session.py", line 157, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\metadata\__init__.py", line 24, in get_default_environment
    from .pkg_resources import Environment
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 9, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
Traceback (most recent call last):
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Scripts\pip-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\main.py", line 70, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\base_command.py", line 101, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\req_command.py", line 144, in handle_pip_version_check
    session = self._build_session(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\cli\req_command.py", line 89, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\network\session.py", line 282, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\network\session.py", line 157, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\metadata\__init__.py", line 24, in get_default_environment
    from .pkg_resources import Environment
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 9, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\rmundkowsky\Miniconda3\envs\vectordb\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

(vectordb) C:\Users\rmundkowsky\git\aiad\backend-tools\connect_to_vector_database>

### Steps/Code To Reproduce behavior

```markdown
pip install "pymilvus>=2.3.1"
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): Windows 10 Enterprise running Python 3.12.0
- Method of installation (Docker, or from source): via pip
- Milvus version (v0.3.1, or v0.4.0): n/a can't get package even installed
- Milvus configuration (Settings you made in `server_config.yaml`): n/a can't get package even installed
```

**Comment by rmundkowsky** [comment]
well, i upgraded pip and now I get this error:

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\rmundkowsky\\AppData\\Local\\Temp\\pip-install-kzxo93kb\\grpcio_84184c1c147a48b9a1a13afc5da73e05\\third_party/boringssl-with-bazel/src/pki/testdata/verify_certificate_chain_unittest/intermediate-wrong-signature-no-authority-key-identifier/generate-chains.py'

Which makes me think that  pymilvus is not supported on Windows?

**Comment by rmundkowsky** [comment]
Well, downgrade python to 3.9.12 and seems to work on Windows, so guess this is a Python 3.12 issue.

**Comment by XuanYang-cn** [comment]
Yes, We're still working on pymilvus supporting python3.12

**Comment by rmundkowsky** [comment]
would be nice if you marked which versions work with which versions of Python.
